"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "nodes": [
        { "id": "Before time", "group": 0 },
        { "id": "House", "group": 1 },
        { "id": "Hip House", "group": 1 },
        { "id": "Deep House", "group": 1 },
        { "id": "Jazzy House", "group": 1 },
        { "id": "Garage", "group": 1 },
        { "id": "Disco House", "group": 1 },
        { "id": "Funky House", "group": 1 },
        { "id": "Nu Disco", "group": 1 },
        { "id": "Speed Garage", "group": 1 },
        { "id": "Acid House", "group": 1 },
        { "id": "Tech House", "group": 1 },
        { "id": "Detroit Techno", "group": 2 },
        { "id": "Techno", "group": 2 },
        { "id": "Minimial Techno", "group": 2 },
        { "id": "Trance", "group": 2 },
        { "id": "Psy Trance", "group": 2 },
        { "id": "Melodic Trance", "group": 2 },
        { "id": "Progressive Trance", "group": 2 },
        { "id": "Hardcore", "group": 2 },
        { "id": "Gabber", "group": 3 },
        { "id": "Happy Hardcore", "group": 3 },
        { "id": "Hardstyle", "group": 3 },
        { "id": "Dub", "group": 4 },
        { "id": "Jungle", "group": 4 },
        { "id": "Breakbeat", "group": 5 },
        { "id": "Drum & Bass", "group": 5 },
        { "id": "Dub Step", "group": 5 },
        { "id": "Hard Step", "group": 5 }
    ],
    "links": [
        { "source": "Before time", "target": "House", value: 7 },
        { "source": "House", "target": "Hip House", value: 12 },
        { "source": "House", "target": "Deep House", value: 12 },
        { "source": "Deep House", "target": "Jazzy House", value: 12 },
        { "source": "Deep House", "target": "Garage", value: 12 },
        { "source": "House", "target": "Disco House", value: 12 },
        { "source": "Disco House", "target": "Funky House", value: 12 },
        { "source": "House", "target": "Nu Disco", value: 13 },
        { "source": "Garage", "target": "Speed Garage", value: 13 },
        { "source": "House", "target": "Acid House", value: 13 },
        { "source": "House", "target": "Tech House", value: 13 },
        { "source": "Before time", "target": "Detroit Techno", value: 13 },
        { "source": "Detroit Techno", "target": "Techno", value: 13 },
        { "source": "Techno", "target": "Minimial Techno", value: 13 },
        { "source": "Detroit Techno", "target": "Trance", value: 13 },
        { "source": "Trance", "target": "Psy Trance", value: 15 },
        { "source": "Trance", "target": "Melodic Trance", value: 15 },
        { "source": "Trance", "target": "Progressive Trance", value: 15 },
        { "source": "Before time", "target": "Hardcore", value: 17 },
        { "source": "Hardcore", "target": "Happy Hardcore", value: 17 },
        { "source": "Hardcore", "target": "Gabber", value: 17 },
        { "source": "Gabber", "target": "Hardstyle", value: 17 },
        { "source": "Before time", "target": "Dub", value: 18 },
        { "source": "Dub", "target": "Jungle", value: 18 },
        { "source": "Before time", "target": "Breakbeat", value: 21 },
        { "source": "Breakbeat", "target": "Drum & Bass", value: 21 },
        { "source": "Drum & Bass", "target": "Dub Step", value: 21 },
        { "source": "Drum & Bass", "target": "Hard Step", value: 21 },
    ]
};
//# sourceMappingURL=electronic-genres.js.map