version: '3.4'

services:
  prometheus:
    build:
      context: prometheus
    image: my-prometheus:latest
    container_name: my-prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      local:
        aliases:
          - prometheus.home-recipes.com

  grafana:
    build:
      context: grafana
    image: my-grafana:latest
    container_name: my-grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      local:
        aliases:
          - grafana.home-recipes.com

  home-recipes:
    image: kaushikchaubal/home-recipes
    container_name: home-recipes
    ports:
      - 50000:50000
      - 2112:2112
    networks:
      local:
        aliases:
          - home-recipes.com

networks:
  local: