language: python
python:
    - "2.7"
    - "3.5"

install:
    - pip install -e .[test]

script: py.test tests --cov=tests --cov-report term-missing

notifications:
    email: false

after_success:
  - coveralls
